/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SERVIDOR
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        JButton botonesH[]={cmdCrear,cmdLimpiar};
        JButton botonesD[]={cmdLlenadoManual,cmdOperacion,cmdLlenadoAuto};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroFilas = new javax.swing.JTextField();
        txtNumeroColumnas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdLlenadoAuto = new javax.swing.JButton();
        cmdOperacion = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdLlenadoManual = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaInicial = new javax.swing.JTable();
        cmbOpciones = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTablaResultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos principales:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(255, 102, 51))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Numero de filas:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Numero de columnas:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtNumeroFilas.setBackground(new java.awt.Color(255, 204, 153));
        txtNumeroFilas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroFilasKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 50, 30));

        txtNumeroColumnas.setBackground(new java.awt.Color(255, 204, 153));
        txtNumeroColumnas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroColumnasKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 50, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 300, 150));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setBackground(new java.awt.Color(204, 204, 255));
        cmdCrear.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 40));

        cmdLlenadoAuto.setBackground(new java.awt.Color(204, 204, 255));
        cmdLlenadoAuto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdLlenadoAuto.setText("Llenado automatico");
        cmdLlenadoAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoAutoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenadoAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 170, 40));

        cmdOperacion.setBackground(new java.awt.Color(204, 204, 255));
        cmdOperacion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdOperacion.setText("Operación");
        cmdOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOperacionActionPerformed(evt);
            }
        });
        jPanel3.add(cmdOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 110, 40));

        cmdLimpiar.setBackground(new java.awt.Color(204, 204, 255));
        cmdLimpiar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 90, 40));

        cmdLlenadoManual.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdLlenadoManual.setText("Llenado Manual");
        cmdLlenadoManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoManualActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenadoManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 150, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 450, 150));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("MATRICES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        tblTablaInicial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblTablaInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTablaInicial);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 430, 270));

        cmbOpciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diagonal segundaria", "Triaungular superior", "Triaungular inferior", "Transpuesta", "Letra A", "Letra Z", "Letra T", "Letra V", "Letra E", "Letra F", "Letra P", "Letra I", "Letra N", "Letra Y", "Letra X" }));
        jPanel1.add(cmbOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 140, 30));

        tblTablaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblTablaResultado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 430, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1114, 616));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int nf, nc;
        DefaultTableModel tm, tm2;

        if (txtNumeroFilas.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el numero de columnas", "Error", JOptionPane.ERROR_MESSAGE);
            txtNumeroFilas.requestFocusInWindow();
            
        } else if (txtNumeroColumnas.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el numero de filas", "Error", JOptionPane.ERROR_MESSAGE);
            txtNumeroColumnas.requestFocusInWindow();
            
        } else {
        nf = Integer.parseInt(txtNumeroFilas.getText());
        nc = Integer.parseInt(txtNumeroColumnas.getText());
        
        if (nc != nf) {
            Helper.mensaje(this, "Digite el mismo numero de filas y columnas", 2);
            txtNumeroFilas.setText("");
            txtNumeroColumnas.setText("");
            txtNumeroFilas.requestFocusInWindow();
        } else if (nf == 0) {
            Helper.mensaje(this, "Por favor, digite un numero diferente", 3);
            txtNumeroFilas.requestFocusInWindow();
            txtNumeroFilas.selectAll();
        } else if (nc == 0) {
            Helper.mensaje(this, "Por favor, digite un numero diferente", 3);
            txtNumeroColumnas.selectAll();
        }else if (nf<10 && nc<10){
          Helper.mensaje(this, "Por favor, digite un numero mayor que 10", 2);
          txtNumeroFilas.setText("");
          txtNumeroColumnas.setText("");
          txtNumeroFilas.requestFocusInWindow();
        } else if (nf>=20 && nc>=20){
          Helper.mensaje(this, "Por favor, digite un numero menor que 20", 2);
          txtNumeroFilas.setText("");
          txtNumeroColumnas.setText("");
          txtNumeroFilas.requestFocusInWindow();  
        } else {
        tm = (DefaultTableModel) tblTablaInicial.getModel();
        tm2 = (DefaultTableModel) tblTablaResultado.getModel();

        tm.setRowCount(nf);
        tm.setColumnCount(nc);

        tm2.setRowCount(nf);
        tm2.setColumnCount(nc);
        
        JButton botonesH[] = {cmdLlenadoAuto, cmdLlenadoManual, cmdLimpiar};
        JButton botonesD[] = {cmdCrear, cmdOperacion};

            Helper.habilitarBotones(botonesH);
            Helper.deshabilitarBotones(botonesD);
        }
        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOperacionActionPerformed
        int op, nf, nc, aux;

        op = cmbOpciones.getSelectedIndex();
        Helper.limpiartabla(tblTablaResultado);

        switch (op) {
            case 0:
                Helper.DiagonalSegundaria(tblTablaInicial, tblTablaResultado);
                break;

            case 1:
                Helper.TriangularS(tblTablaInicial, tblTablaResultado);
                break;

            case 2:
                Helper.TriangularIn(tblTablaInicial, tblTablaResultado);
                break;

            case 3:
                Helper.Transpuesta(tblTablaInicial, tblTablaResultado);
                break;

            case 4:
                Helper.LetraA(tblTablaInicial, tblTablaResultado);
                break;
            case 5:
                Helper.LetraZ(tblTablaInicial, tblTablaResultado);
                break;

            case 6:
                Helper.LetraT(tblTablaInicial, tblTablaResultado);
                break;

            case 7:
                Helper.LetraV(tblTablaInicial, tblTablaResultado);
                break;
            case 8:
                Helper.LetraE(tblTablaInicial, tblTablaResultado);
                break;
            case 9:
                Helper.LetraF(tblTablaInicial, tblTablaResultado);
                break;
            case 10:
                Helper.LetraP(tblTablaInicial, tblTablaResultado);
                break;
            case 11:
                Helper.LetraI(tblTablaInicial, tblTablaResultado);
                break;
            case 12:
                Helper.LetraN(tblTablaInicial, tblTablaResultado);
                break;
            case 13:
                Helper.LetraY(tblTablaInicial, tblTablaResultado);
                break;
            case 14:
                Helper.LetraX(tblTablaInicial, tblTablaResultado);
                break;
        }
        JButton botonesH[]={cmdOperacion,cmdLimpiar};
        JButton botonesD[]={cmdCrear,cmdLlenadoAuto,cmdLlenadoManual};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD); 
        
        
    }//GEN-LAST:event_cmdOperacionActionPerformed

    private void cmdLlenadoAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoAutoActionPerformed
        int nf,nc,n;
        
        nc = tblTablaInicial.getColumnCount();
        nf =  tblTablaInicial.getRowCount();
        
        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
              n = (int) (Math.random()*50 + 1); 
              tblTablaInicial.setValueAt(n,i,j);
            }
        }
        JButton botonesH[]={cmdOperacion,cmdLimpiar};
        JButton botonesD[]={cmdCrear,cmdLlenadoAuto,cmdLlenadoManual};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);   
        
    }//GEN-LAST:event_cmdLlenadoAutoActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
      int nf,nc;
      nc=tblTablaInicial.getColumnCount();
      nf=tblTablaInicial.getRowCount();
      DefaultTableModel tm,tm2;
      
      txtNumeroColumnas.setText("");
      txtNumeroFilas.setText("");
      cmbOpciones.setSelectedIndex(0);
      
      tm=(DefaultTableModel) tblTablaInicial.getModel();
      tm2=(DefaultTableModel) tblTablaResultado.getModel();
      
       tm.setRowCount(0);
       tm.setColumnCount(0);
       
       tm2.setRowCount(0);
       tm2.setColumnCount(0);
       
        JButton botonesH[]={cmdCrear,cmdLimpiar};
        JButton botonesD[]={cmdLlenadoManual,cmdOperacion,cmdLlenadoAuto};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
      
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void txtNumeroFilasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroFilasKeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();    
          } 
    }//GEN-LAST:event_txtNumeroFilasKeyTyped

    private void txtNumeroColumnasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroColumnasKeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();    
          } 
    }//GEN-LAST:event_txtNumeroColumnasKeyTyped

    private void cmdLlenadoManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoManualActionPerformed
        int nf, nc;
       int n;
        int sw, res;

        nc = tblTablaInicial.getColumnCount();
        nf = tblTablaInicial.getRowCount();

        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                n = (int) (Math.random() * 50 + 1);
                tblTablaInicial.setValueAt(n, i, j);
                do {
                    sw = 1;
                    try {
                        n = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el elemeto en la posicion ["+i+"]"+"["+j+"]").trim());
                        tblTablaInicial.setValueAt(n, i, j);
                    } catch (NumberFormatException e) {
                        Helper.mensaje(this, "Digite un numero valido",3);
                        sw = 0;
                    } catch (NullPointerException e) {
                        res = JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            sw = 1;
                            i = nf;
                            j = nc;
                            
                            Helper.porDefectoTabla(tblTablaInicial);
                            Helper.porDefectoTabla(tblTablaResultado);
                        } else {
                            sw = 0;
                        }
                    }
                } while (sw == 0);
            }
        }
        JButton botonesH[]={cmdOperacion,cmdLimpiar};
        JButton botonesD[]={cmdLlenadoManual,cmdCrear,cmdLlenadoAuto};
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
        
    }//GEN-LAST:event_cmdLlenadoManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbOpciones;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdLlenadoAuto;
    private javax.swing.JButton cmdLlenadoManual;
    private javax.swing.JButton cmdOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTablaInicial;
    private javax.swing.JTable tblTablaResultado;
    private javax.swing.JTextField txtNumeroColumnas;
    private javax.swing.JTextField txtNumeroFilas;
    // End of variables declaration//GEN-END:variables
}
